import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:geolocator/geolocator.dart';
import 'package:geocoding/geocoding.dart';
import 'geocoding_service.dart';
class SimpleStopService {
  static const double _proximityThreshold = 100.0;
  static Future<void> createStopFromAddress({
    required String passengerId,
    required String passengerName,
    required String address,
    required String regionId,
  }) async {
    try {
      if (address.trim().isEmpty) return;
      final coordinates = await _getCoordinatesFromAddress(address);
      if (coordinates == null) {
        print('Adres koordinatlara çevrilemedi: $address');
        return;
      }
      final nearbyStop = await _findNearbyStop(
        coordinates['lat']!,
        coordinates['lng']!,
        regionId,
      );
      if (nearbyStop != null) {
        await _addPassengerToExistingStop(
          nearbyStop['id'],
          passengerId,
          passengerName,
          address,
        );
        print('Yolcu mevcut durağa eklendi: ${nearbyStop['name']}');
      } else {
        await _createNewStop(
          passengerId: passengerId,
          passengerName: passengerName,
          address: address,
          latitude: coordinates['lat']!,
          longitude: coordinates['lng']!,
          regionId: regionId,
        );
        print('Yeni durak oluşturuldu: $address');
      }
    } catch (e) {
      print('Durak oluşturma hatası: $e');
    }
  }
  static Future<Map<String, double>?> _getCoordinatesFromAddress(
      String address) async {
    try {
      final googleCoordinates =
          await GeocodingService.getCoordinatesFromAddress(address);
      if (googleCoordinates != null) {
        return {
          'lat': googleCoordinates['latitude']!,
          'lng': googleCoordinates['longitude']!,
        };
      }
      final locations = await locationFromAddress(address);
      if (locations.isNotEmpty) {
        final location = locations.first;
        final coordinates = {
          'lat': location.latitude,
          'lng': location.longitude,
        };
        print(
            '[SimpleStopService] ✅ Flutter geocoding ile koordinat bulundu: $coordinates');
        return coordinates;
      }
    } catch (e) {
      print('[SimpleStopService] ❌ Geocoding hatası: $e');
    }
    return null;
  }
  static Future<Map<String, dynamic>?> _findNearbyStop(
    double latitude,
    double longitude,
    String regionId,
  ) async {
    try {
      final stopsSnapshot = await FirebaseFirestore.instance
          .collection('enhanced_stops')
          .where('regionId', isEqualTo: regionId)
          .where('isActive', isEqualTo: true)
          .get();
      for (final doc in stopsSnapshot.docs) {
        final data = doc.data();
        final stopLat = data['latitude'] as double?;
        final stopLng = data['longitude'] as double?;
        if (stopLat != null && stopLng != null) {
          final distance = _calculateDistance(
            latitude,
            longitude,
            stopLat,
            stopLng,
          );
          if (distance <= _proximityThreshold) {
            return {
              'id': doc.id,
              'name': data['name'],
              'distance': distance,
              ...data,
            };
          }
        }
      }
    } catch (e) {
      print('Yakın durak arama hatası: $e');
    }
    return null;
  }
  static Future<void> _createNewStop({
    required String passengerId,
    required String passengerName,
    required String address,
    required double latitude,
    required double longitude,
    required String regionId,
  }) async {
    try {
      final stopRef =
          FirebaseFirestore.instance.collection('enhanced_stops').doc();
      await stopRef.set({
        'id': stopRef.id,
        'name': 'Durak - $address',
        'address': address,
        'latitude': latitude,
        'longitude': longitude,
        'regionId': regionId,
        'passengerIds': [passengerId],
        'passengerNames': [passengerName],
        'addresses': [address],
        'passengerCount': 1,
        'isActive': true,
        'isAutoGenerated': true,
        'createdAt': FieldValue.serverTimestamp(),
        'lastUpdated': FieldValue.serverTimestamp(),
        'type': 'passenger_address',
      });
      print('Yeni durak oluşturuldu: ${stopRef.id}');
    } catch (e) {
      print('Durak oluşturma hatası: $e');
    }
  }
  static Future<void> _addPassengerToExistingStop(
    String stopId,
    String passengerId,
    String passengerName,
    String address,
  ) async {
    try {
      final stopRef =
          FirebaseFirestore.instance.collection('enhanced_stops').doc(stopId);
      await FirebaseFirestore.instance.runTransaction((transaction) async {
        final stopDoc = await transaction.get(stopRef);
        if (!stopDoc.exists) {
          print('Durak bulunamadı: $stopId');
          return;
        }
        final data = stopDoc.data();
        if (data == null) {
          print('Durak verisi null: $stopId');
          return;
        }
        final passengerIds = List<String>.from(data['passengerIds'] ?? []);
        final passengerNames = List<String>.from(data['passengerNames'] ?? []);
        final addresses = List<String>.from(data['addresses'] ?? []);
        final existingIndex = passengerIds.indexOf(passengerId);
        if (existingIndex != -1) {
          passengerNames[existingIndex] = passengerName;
          addresses[existingIndex] = address;
        } else {
          passengerIds.add(passengerId);
          passengerNames.add(passengerName);
          addresses.add(address);
        }
        transaction.update(stopRef, {
          'passengerIds': passengerIds,
          'passengerNames': passengerNames,
          'addresses': addresses,
          'passengerCount': passengerIds.length,
          'lastUpdated': FieldValue.serverTimestamp(),
        });
      });
    } catch (e) {
      print('Durağa yolcu ekleme hatası: $e');
    }
  }
  static Future<void> removePassengerFromStop(
    String passengerId,
    String regionId,
  ) async {
    try {
      final stopsSnapshot = await FirebaseFirestore.instance
          .collection('enhanced_stops')
          .where('regionId', isEqualTo: regionId)
          .where('passengerIds', arrayContains: passengerId)
          .get();
      for (final doc in stopsSnapshot.docs) {
        final stopRef = doc.reference;
        await FirebaseFirestore.instance.runTransaction((transaction) async {
          final stopDoc = await transaction.get(stopRef);
          if (!stopDoc.exists) return;
          final data = stopDoc.data();
          if (data == null) return;
          final passengerIds = List<String>.from(data['passengerIds'] ?? []);
          final passengerNames =
              List<String>.from(data['passengerNames'] ?? []);
          final addresses = List<String>.from(data['addresses'] ?? []);
          final passengerIndex = passengerIds.indexOf(passengerId);
          if (passengerIndex == -1) return;
          passengerIds.removeAt(passengerIndex);
          passengerNames.removeAt(passengerIndex);
          addresses.removeAt(passengerIndex);
          if (passengerIds.isEmpty && data['isAutoGenerated'] == true) {
            transaction.delete(stopRef);
            print('Otomatik oluşturulmuş boş durak silindi: ${doc.id}');
          } else {
            transaction.update(stopRef, {
              'passengerIds': passengerIds,
              'passengerNames': passengerNames,
              'addresses': addresses,
              'passengerCount': passengerIds.length,
              'lastUpdated': FieldValue.serverTimestamp(),
            });
            print('Yolcu duraktan kaldırıldı: $passengerId');
          }
        });
      }
    } catch (e) {
      print('Yolcu kaldırma hatası: $e');
    }
  }
  static Future<List<Map<String, dynamic>>> getStopsForRegion(
      String regionId) async {
    try {
      final stopsSnapshot = await FirebaseFirestore.instance
          .collection('enhanced_stops')
          .where('regionId', isEqualTo: regionId)
          .where('isActive', isEqualTo: true)
          .orderBy('createdAt', descending: true)
          .get();
      return stopsSnapshot.docs.map((doc) {
        final data = doc.data();
        return {
          'id': doc.id,
          ...data,
        };
      }).toList();
    } catch (e) {
      print('Durakları getirme hatası: $e');
      return [];
    }
  }
  static Future<List<Map<String, dynamic>>> getAllStops() async {
    try {
      final stopsSnapshot = await FirebaseFirestore.instance
          .collection('enhanced_stops')
          .where('isActive', isEqualTo: true)
          .orderBy('createdAt', descending: true)
          .get();
      return stopsSnapshot.docs.map((doc) {
        final data = doc.data();
        return {
          'id': doc.id,
          ...data,
        };
      }).toList();
    } catch (e) {
      print('Tüm durakları getirme hatası: $e');
      return [];
    }
  }
  static Future<bool> deleteStop(String stopId) async {
    try {
      await FirebaseFirestore.instance
          .collection('enhanced_stops')
          .doc(stopId)
          .update({
        'isActive': false,
        'deletedAt': FieldValue.serverTimestamp(),
      });
      return true;
    } catch (e) {
      print('Durak silme hatası: $e');
      return false;
    }
  }
  static Future<List<Map<String, dynamic>>> getStopsForDriver(
      String driverId) async {
    try {
      print('🔍 Şoför durakları getiriliyor. Şoför ID: $driverId');
      final driverDoc = await FirebaseFirestore.instance
          .collection('drivers')
          .doc(driverId)
          .get();
      if (!driverDoc.exists) {
        print('❌ Şoför bulunamadı: $driverId');
        return [];
      }
      final driverData = driverDoc.data()!;
      final regionId = driverData['regionId'];
      final vehiclePlate = driverData['vehiclePlate'] ?? driverData['plate'];
      print('📍 Şoför bilgileri - Bölge: $regionId, Plaka: $vehiclePlate');
      if (regionId == null) {
        print('❌ Şoförün bölgesi tanımlı değil: $driverId');
        return [];
      }
      final col = FirebaseFirestore.instance.collection('enhanced_stops');
      QuerySnapshot<Map<String, dynamic>> snapCreated;
      try {
        snapCreated = await col
            .where('regionId', isEqualTo: regionId)
            .where('isActive', isEqualTo: true)
            .where('createdFromMap', isEqualTo: true)
            .orderBy('createdAt', descending: true)
            .get();
      } catch (_) {
        snapCreated = await col
            .where('regionId', isEqualTo: regionId)
            .where('isActive', isEqualTo: true)
            .where('createdFromMap', isEqualTo: true)
            .get();
      }
      QuerySnapshot<Map<String, dynamic>> snapSource;
      try {
        snapSource = await col
            .where('regionId', isEqualTo: regionId)
            .where('isActive', isEqualTo: true)
            .where('source', isEqualTo: 'map_selection')
            .orderBy('createdAt', descending: true)
            .get();
      } catch (_) {
        snapSource = await col
            .where('regionId', isEqualTo: regionId)
            .where('isActive', isEqualTo: true)
            .where('source', isEqualTo: 'map_selection')
            .get();
      }
      final Map<String, QueryDocumentSnapshot<Map<String, dynamic>>> byId = {};
      for (final d in [...snapCreated.docs, ...snapSource.docs]) {
        byId[d.id] = d;
      }
      final stopsDocs = byId.values.toList();
      print('🚏 Bölgedeki aktif HARİTA durağı: ${stopsDocs.length}');
      final List<Map<String, dynamic>> driverStops = [];
      for (final doc in stopsDocs) {
        final stopData = doc.data();
        final passengerIds = List<String>.from(stopData['passengerIds'] ?? []);
        print(
            '🔍 Durak kontrol ediliyor: ${doc.id}, Yolcu sayısı: ${passengerIds.length}');
        final List<String> assignedPassengerIds = [];
        final List<String> assignedPassengerNames = [];
        final List<String> assignedAddresses = [];
        for (int i = 0; i < passengerIds.length; i++) {
          final passengerId = passengerIds[i];
          try {
            final passengerDoc = await FirebaseFirestore.instance
                .collection('passengers')
                .doc(passengerId)
                .get();
            if (passengerDoc.exists) {
              final passengerData = passengerDoc.data()!;
              final passengerDriverId = passengerData['driverId'];
              final passengerVehiclePlate = passengerData['vehiclePlate'];
              print(
                  '👤 Yolcu kontrol: $passengerId, Atanmış şoför: $passengerDriverId, Plaka: $passengerVehiclePlate');
              bool isAssigned = false;
              if (passengerDriverId == driverId) {
                isAssigned = true;
                print('✅ Yolcu şoför ID ile eşleşti');
              } else if (vehiclePlate != null &&
                  passengerVehiclePlate == vehiclePlate) {
                isAssigned = true;
                print('✅ Yolcu plaka ile eşleşti');
              }
              if (isAssigned) {
                assignedPassengerIds.add(passengerId);
                final passengerNames =
                    List<String>.from(stopData['passengerNames'] ?? []);
                final addresses =
                    List<String>.from(stopData['addresses'] ?? []);
                if (i < passengerNames.length) {
                  assignedPassengerNames.add(passengerNames[i]);
                } else {
                  assignedPassengerNames
                      .add(passengerData['name'] ?? 'İsimsiz');
                }
                if (i < addresses.length) {
                  assignedAddresses.add(addresses[i]);
                } else {
                  assignedAddresses
                      .add(passengerData['address'] ?? 'Adres yok');
                }
              }
            } else {
              print('❌ Yolcu belgesi bulunamadı: $passengerId');
            }
          } catch (e) {
            print('❌ Yolcu kontrol hatası ($passengerId): $e');
          }
        }
        if (assignedPassengerIds.isNotEmpty) {
          final driverStop = {
            'id': doc.id,
            ...stopData,
            'assignedPassengerIds': assignedPassengerIds,
            'assignedPassengerNames': assignedPassengerNames,
            'assignedAddresses': assignedAddresses,
            'assignedPassengerCount': assignedPassengerIds.length,
          };
          driverStops.add(driverStop);
          print(
              '✅ Durak eklendi: ${doc.id}, Atanmış yolcu sayısı: ${assignedPassengerIds.length}');
        } else {
          print('⚠️ Durakta şoföre atanmış yolcu yok: ${doc.id}');
        }
      }
      print('📊 Şoför için toplam durak sayısı: ${driverStops.length}');
      try {
        final sortedStops = await _sortStopsByDistance(driverStops, driverId);
        print('📍 Duraklar mesafeye göre sıralandı');
        return sortedStops;
      } catch (e) {
        print('⚠️ Durak sıralama hatası: $e, sıralanmamış liste döndürülüyor');
        return driverStops;
      }
    } catch (e) {
      print('❌ Şoför durakları getirme hatası: $e');
      return [];
    }
  }
  static Future<List<Map<String, dynamic>>> _sortStopsByDistance(
      List<Map<String, dynamic>> stops, String driverId) async {
    if (stops.isEmpty) return stops;
    try {
      final driverLocation = await _getDriverCurrentLocation(driverId);
      if (driverLocation == null) {
        print('⚠️ Şoför konumu alınamadı, sıralama yapılmıyor');
        return stops;
      }
      final stopsWithDistance = stops.map((stop) {
        final distance = _calculateDistance(
          driverLocation['latitude']!,
          driverLocation['longitude']!,
          stop['latitude']?.toDouble() ?? 0.0,
          stop['longitude']?.toDouble() ?? 0.0,
        );
        return {
          ...stop,
          'distanceFromDriver': distance,
        };
      }).toList();
      stopsWithDistance.sort((a, b) => (a['distanceFromDriver'] as double)
          .compareTo(b['distanceFromDriver'] as double));
      print(
          '📏 Duraklar mesafeye göre sıralandı. En yakın durak: ${stopsWithDistance.first['distanceFromDriver']?.toStringAsFixed(0)}m');
      return stopsWithDistance;
    } catch (e) {
      print('❌ Durak sıralama hatası: $e');
      return stops;
    }
  }
  static Future<Map<String, double>?> _getDriverCurrentLocation(
      String driverId) async {
    try {
      final position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high,
      );
      return {
        'latitude': position.latitude,
        'longitude': position.longitude,
      };
    } catch (e) {
      print('❌ Şoför konumu alma hatası: $e');
      try {
        final driverDoc = await FirebaseFirestore.instance
            .collection('drivers')
            .doc(driverId)
            .get();
        if (driverDoc.exists) {
          final data = driverDoc.data()!;
          final lat = data['currentLatitude']?.toDouble();
          final lng = data['currentLongitude']?.toDouble();
          if (lat != null && lng != null) {
            print('📍 Firestore\'dan son bilinen konum alındı');
            return {
              'latitude': lat,
              'longitude': lng,
            };
          }
        }
      } catch (firestoreError) {
        print('❌ Firestore konum alma hatası: $firestoreError');
      }
      return null;
    }
  }
  static double _calculateDistance(
      double lat1, double lon1, double lat2, double lon2) {
    return Geolocator.distanceBetween(lat1, lon1, lat2, lon2);
  }
}
